export const ITEM_TYPES = {
    RAW_MATERIAL: 'RAW_MATERIAL',
    WORK_IN_PROGRESS: 'WORK_IN_PROGRESS',
    FINISHED_GOOD: 'FINISHED_GOOD',
    PACKAGING: 'PACKAGING'
};

export const ZONE_TYPES = {
    GENERAL: 'GENERAL',
    COLD_STORAGE: 'COLD_STORAGE',
    HAZMAT: 'HAZMAT',
    RECEIVING: 'RECEIVING',
    SHIPPING: 'SHIPPING',
    QUARANTINE: 'QUARANTINE'
};

export const USER_ROLES = {
    SUPER_ADMIN: 'SUPER_ADMIN',
    COMPANY_ADMIN: 'COMPANY_ADMIN',
    OPS_MANAGER: 'OPS_MANAGER',
    WAREHOUSE_STAFF: 'WAREHOUSE_STAFF',
    VENDOR: 'VENDOR'
};

export const PO_STATUS = {
    DRAFT: 'DRAFT',
    PENDING_APPROVAL: 'PENDING_APPROVAL',
    APPROVED: 'APPROVED',
    REJECTED: 'REJECTED',
    PARTIALLY_RECEIVED: 'PARTIALLY_RECEIVED',
    COMPLETED: 'COMPLETED',
    CANCELLED: 'CANCELLED'
};
